Continue workflow if Copy API spec step fails (#1130)
* Continue workflow if Copy API spec step fails

* Add failure check

diff --git a/.github/workflows/deploy-stage.yml b/.github/workflows/deploy-stage.yml
--- a/.github/workflows/deploy-stage.yml
+++ b/.github/workflows/deploy-stage.yml
@@ -40,15 +40,22 @@ jobs:
             ${{ runner.os }}-
       - run: yarn --frozen-lockfile
       - name: Copy API Spec
+        id: copy_api_spec
         env:
           GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
         run: |
           git clone https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.com/limelight-networks/cdn-analytics/core/server/eq-metrics-public-api.git
           rsync -av "eq-metrics-public-api/src/api/public-docs/components/" "rest_api/openapi/components"
           rsync -av "eq-metrics-public-api/src/api/public-docs/paths/" "rest_api/openapi/paths"
-
-          # copy files to destination
-
+        continue-on-error: true
+      - name: Check Copy API Spec Status
+        if: always()
+        run: |
+          if [ ${{ steps.copy_api_spec.outcome }} == "failure" ]; then
+            echo "COPY_API_SPEC_FAILED=true" >> $GITHUB_ENV
+          else
+            echo "COPY_API_SPEC_FAILED=false" >> $GITHUB_ENV
+          fi
       - name: Deploy to docs.edg.io (stage)
         run: |
           yarn edgio:deploy --branch=$BRANCH_NAME --token=${{secrets.edgio_prod_deploy_token}} --environment=default
@@ -96,3 +103,10 @@ jobs:
             - Permalink Preview: ${{ steps.deploy.outputs.buildUrl }}
             - Branch Preview: ${{ steps.deploy.outputs.branchUrl }}
             - Edge URL: ${{ steps.deploy.outputs.edgeUrl }}
+      - name: Final Check for Failures
+        if: always()
+        run: |
+          if [ "$COPY_API_SPEC_FAILED" == "true" ]; then
+            echo "One or more steps failed."
+            exit 1
+          fi
